name: Random Tweet Bot

on:
  schedule:
  - cron: '0 */3 * * *'    # at minute 0 every 3rd hour
  - cron: '30 1-23/3 * * *' # at minute 30 starting from hour 1 every 3rd hour
  workflow_dispatch:


jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run bot with random chance
        env:
           GEMINI_API_KEY2: ${{ secrets.GEMINI_API_KEY2 }}
           TWITTER_BEARER_TOKEN2: ${{ secrets.TWITTER_BEARER_TOKEN2 }}
           TWITTER_API_KEY2: ${{ secrets.TWITTER_API_KEY2 }}
           TWITTER_API_SECRET2: ${{ secrets.TWITTER_API_SECRET2 }}
           TWITTER_ACCESS_TOKEN2: ${{ secrets.TWITTER_ACCESS_TOKEN2 }}
           TWITTER_ACCESS_SECRET2: ${{ secrets.TWITTER_ACCESS_SECRET2 }}
        run: python tweet_random.py
