name: tweet_bot_ai

on:
  push:
    paths:
      - 'tweet.py'
      - '.github/workflows/bot.yml'
  schedule:
    - cron: '0 * * * *'  # Every hour UTC
  workflow_dispatch:

jobs:
  tweet_job:
    name: 🐦 Post a Tweet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tweepy python-dotenv google-genai

      - name: Create .env from secrets
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}" >> .env
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> .env

      - name: Run tweet.py
        run: python tweet.py
