# .github/workflows/bot.yml

name: tweet_bot_ai

on:
  # Schedule each script separately:
  # → tweet.py every 30 minutes (minutes 0 & 30)
  schedule:
    - cron: '0 * * * *'   # At minute 0 and 30 every hour UTC → run tweet.py
  # → like.py at minute 0 every hour
    - cron: '0 * * * *'      # At minute 0 each hour UTC → run like.py
  # → reply.py at minute 15 and 45 every hour
    - cron: '15,45 * * * *'  # At minute 15 & 45 UTC → run reply.py
  # → quote.py every 90 minutes: 00:00, 01:30, 03:00, 04:30, etc.
    - cron: '0  * * * *'     # We'll run quote.py manually via a conditional below
  # Allow manual dispatch
  workflow_dispatch:

jobs:
  tweet_job:
    name: 🐦 Post a Tweet
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && contains(github.event.schedule, '*/30')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tweepy python-dotenv google-genai

      - name: Create .env from secrets
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}" >> .env
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> .env

      - name: Run tweet.py
        run: python tweet.py

  like_job:
    name: ❤️ Like Tweets
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && contains(github.event.schedule, '0 *')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tweepy python-dotenv google-genai

      - name: Create .env from secrets
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}" >> .env
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> .env

      - name: Run like.py
        run: python like.py

  reply_job:
    name: 🗨️ Reply to Mentions
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && contains(github.event.schedule, '15,45')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tweepy python-dotenv google-genai

      - name: Create .env from secrets
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}" >> .env
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> .env

      - name: Run reply.py
        run: python reply.py

  quote_job:
    name: 🔁 Quote-Tweet
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && ( 
         startsWith(github.event.schedule, '0 ') ||
         contains(github.event.schedule, '*/90') 
       )
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tweepy python-dotenv google-genai

      - name: Create .env from secrets
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}" >> .env
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> .env

      - name: Run quote.py
        run: python quote.py
